foodstories/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from accounts.views import RegisterView, LoginUserView, ProfileView, CustomPasswordResetConfirmView, ResetPassword, ThePasswordChangeView, EditProfileView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('user-profile/<int:pk>', ProfileView.as_view(), name='user-profile'),
    path('log-out', LogoutView.as_view(), name='log-out'),
    path('reset-password', ResetPassword.as_view(), name='reset-password'),
    path('change-password', ThePasswordChangeView.as_view(), name='change-password'),
    path('edit-profile/<int:pk>/', EditProfileView.as_view(), name='edit_profile'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', CustomPasswordResetConfirmView.as_view(), name = 'password-reset-confirm'),
]

foodstories/foodstories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inventory.urls', namespace='inventory')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('inventory.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

foodstories/inventory/urls.py
from django.urls import path

from . import views

app_name = 'inventory'

from inventory.views import RecipeView

urlpatterns = [
    path('', views.IndexView.as_view(), name='index-page'),
    path('recipes/', views.RecipeView.as_view(), name='recipe-list'),
    path('recipes/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('create-story/', views.CreateRecipeView.as_view(), name='create_story'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('edit-story/<int:pk>/', views.EditRecipeView.as_view(), name='edit_story'),
    path('delete-story/<int:pk>/', views.DeleteRecipeView.as_view(), name='delete_story'),
    
]

foodstories/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    GENDER_CHOICES = (
    ("Male", ("Male")),
    ("Female", ("Female"))
)
    bio = models.TextField(max_length=1000, blank=True)
    profile_pic = models.ImageField(upload_to='images')
    gender = models.CharField(choices=GENDER_CHOICES, max_length=6)
    email = models.EmailField(('email adress'), unique=True, null=True)

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

foodstories/accounts/forms.py
from django import forms
from accounts.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm

class RegisterForm(UserCreationForm):
    password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Password',
                'class' : 'form-control',
            }))

    password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Confirm password',
                'class' : 'form-control',
             }))
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

        widgets = {
            'first_name': forms.TextInput(attrs={'id': 'first_name', 'placeholder': 'Your First Name', 'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'id': 'last_name', 'placeholder': 'Your Last Name', 'class': 'form-control'}),
            'username': forms.TextInput(attrs={'id': 'username', 'placeholder': 'Your Username', 'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'Email', 'class': 'form-control'}),
        }

class LoginForm(AuthenticationForm):
    password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Password',
                'class' : 'form-control',
            }))

    username = forms.CharField(
        widget = forms.TextInput(
            attrs={
                'id': 'username',
                'placeholder': 'Your Username',
                'class': 'form-control'
            }))

    class Meta:
        model = User
        fields = ['username', 'password']

class ResetItDown(PasswordResetForm):
    email = forms.EmailField(
        widget = forms.EmailInput(attrs={
            'placeholder': 'Your Email',
            'class': 'form-control',
        })
    )

class PasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'New password',
                'class' : 'form-control',
             }))
    
    new_password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Re-enter new password',
                'class' : 'form-control',
             }))

    class Meta:
        fields = ("new_password1", 'new_password2', )

class ThePasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Old password',
                'class' : 'form-control',
            }))

    new_password1 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'New password',
                'class' : 'form-control',
            }))

    new_password2 = forms.CharField(
        widget = forms.PasswordInput(
            attrs={
                'placeholder' : 'Re-enter new password',
                'class' : 'form-control',
            }))

    class Meta:
        fields = ("old_password", 'new_password1', 'new_password2', )

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'bio', 'profile_pic']

        widgets = {
            'first_name': forms.TextInput(attrs={'id': 'first_name', 'placeholder': 'First Name',  'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'id': 'last_name', 'placeholder': 'Last Name',  'class': 'form-control'}),
            'username': forms.TextInput(attrs={'id': 'username', 'placeholder': 'Your Username',  'class': 'form-control'}),
            'bio': forms.Textarea(attrs={'id': 'bio', 'placeholder': 'Bio',  'class': 'form-control'}),
            'profile_pic': forms.FileInput(attrs={'id': 'profile_pic', 'placeholder': 'Profile Picture',  'class': 'form-control'}),
        }

foodstories/accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView
from accounts.models import User
from .forms import RegisterForm, LoginForm, ResetItDown, PasswordResetConfirmForm, ThePasswordChangeForm, UpdateProfileForm
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView, PasswordChangeView
from django.core.exceptions import PermissionDenied

# Create your views here.
class RegisterView(CreateView):
    model = User
    template_name = 'register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('inventory:recipe-list')

class LoginUserView(LoginView):
    template_name = 'login.html'
    form_class = LoginForm

class ProfileView(DetailView):
    model = User
    template_name = 'user-profile.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class ResetPassword(PasswordResetView):
    form_class = ResetItDown
    template_name = 'forget_password.html'
    success_url = reverse_lazy('accounts:login')
    email_template_name = 'password_reset_email.html'

class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name= "reset_password.html" 
    success_url = reverse_lazy('accounts:login')
    form_class = PasswordResetConfirmForm

class ThePasswordChangeView(PasswordChangeView):
    template_name = 'change_password.html'
    form_class = ThePasswordChangeForm
    success_url = reverse_lazy('accounts:login')

class EditProfileView(UpdateView):
    model = User
    template_name = 'edit-user.html'
    form_class = UpdateProfileForm
    
    def get_success_url(self):
        return reverse_lazy('accounts:user-profile', kwargs={'pk':self.get_object().id})

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.username != self.get_object().username:
            raise PermissionDenied
        return super(EditProfileView, self).dispatch(request, *args, **kwargs)

foodstories/accounts/templates/change_password.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}

    {% block css %}
    {% endblock %}


{% block content %}

<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST">
                        <div class="form-group">
                            <h4 class="reset center">Change your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.old_password}}
                            {{form.old_password.errors}}
                        </div>
                        <div class="form-group">
                            {{form.new_password1}}
                            {{form.new_password1.errors}}
                        </div>
                        <div class="form-group">
                            {{form.new_password2}}
                            {{form.new_password2.errors}}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Change password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

{% block js %}
{% endblock %}

foodstories/accounts/templates/edit-user.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}
    
    {% block css %}
    {% endblock %}

    {% block content %}

<!-- END nav -->
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST" enctype="multipart/form-data">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.first_name}}
                            {{form.first_name.errors}}
                        </div>
                        <div class="form-group">
                            {{form.last_name}}
                            {{form.last_name.errors}}
                        </div>
                        <div class="form-group">
                            {{form.username}}
                            {{form.username.errors}}
                        </div>
                        <div class="form-group">
                            {{form.bio}}
                            {{form.bio.errors}}
                        </div>
                        <div class="form-group">
                            {{form.profile_pic}}
                            {{form.profile_pic.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

    {% block js %}
    {% endblock %}

foodstories/accounts/templates/forget_password.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}

    {% block css %}
    {% endblock %}


{% block content %}

<!-- END nav -->
 <section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST">
                        <div class="form-group">
                            <h4 class="reset center">Reset password</h4>
                            <h6 class="center">Please enter your email address to request a password reset.</h6>
                        </div>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

{% block js %}
{% endblock %}

foodstories/accounts/templates/login.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}

    {% block css %}
    {% endblock %}


{% block content %}

<!-- END nav -->
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST" enctype="multipart/form-data">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.username}}
                            {{form.username.errors}}
                        </div>
                        <div class="form-group">
                            {{form.password}}
                            {{form.password.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Login" class="btn btn-primary py-3 px-5">
                            <a href="{% url 'accounts:reset-password' %}" class="forgot-password">Forgot password?</a>
                        </div>
                        <div class="form-group">
                            <a href="{% url 'accounts:register' %}" class="">Don't have an account? Sign up</a>
                        </div>
			<div class="form-group center">
                            <a href="#" class="social"><i class="fa fa-facebook social-login fb-color"></i></a>
                            <a href="#" class="social"><i class="fa fa-google-plus social-login google-color"></i></a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

{% block js %}
{% endblock %}

foodstories/accounts/templates/password_reset_email.html
{% load i18n %}
{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
Sifrenizi deyismek ucun bura tiklayin!
{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

foodstories/accounts/templates/register.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}
    
    {% block css %}
    {% endblock %}

    {% block content %}

<!-- END nav -->
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST" enctype="multipart/form-data">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.first_name}}
                            {{form.first_name.errors}}
                        </div>
                        <div class="form-group">
                            {{form.last_name}}
                            {{form.last_name.errors}}
                        </div>
                        <div class="form-group">
                            {{form.username}}
                            {{form.username.errors}}
                        </div>
                        <div class="form-group">
                            {{form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="form-group">
                            {{form.password1}}
                            {{form.password1.errors}}
                        </div>
                        <div class="form-group">
                            {{form.password2}}
                            {{form.password2.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Register" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

    {% block js %}
    {% endblock %}

foodstories/accounts/templates/reset_password.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}

    {% block css %}
    {% endblock %}

    {% block content %}
<!-- END nav -->
<section class="ftco-section contact-section register">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST">
                        <div class="form-group">
                            <h4 class="reset center">Reset your password</h4>
                            <h6 class="center">Please choose a new password to finish signing in.</h6>
                        </div>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.new_password1}}
                            {{form.new_password1.errors}}
                        </div>
                        <div class="form-group">
                            {{form.new_password2}}
                            {{form.new_password2.errors}}
                        </div>
                        <div class="form-group center">
                            <input type="submit" value="Reset password" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>

{% endblock %}

{% block js %}
{% endblock %}

foodstories/accounts/templates/user-profile.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}

    {% block css %}
    {% endblock %}


{% block content %}


    <section class="ftco-section ftco-no-pt ">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="user-profile-side-bar sidebar-wrap">
                        <div class="sidebar-box p-4 about text-center ftco-animate">
                            <h2 class="heading mb-4">About Me</h2>
                            {% if user.profile_pic %}
                        <img src="{{ user.profile_pic.url }}" style="width: 30px; height: 30px; border-radius: 50%;" alt="">
                        {% else %}
                        <img src="{% static 'images/default-profile-icon-16.jpg' %}" style="width: 30px; height: 30px; border-radius: 50%;" alt="">
                        {% endif %}
                            <div class="text pt-4">
                                <p>{{ user.bio }}</p>
                            </div>
                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            
                            <a href="{% url 'accounts:edit_profile' user.pk%}" class="btn btn-hover-color py-2">Edit Profile</a>

                        </div>
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="{% url 'inventory:create_story' %}" class="btn btn-hover-color py-2">Create recipe </a>
                        </div>
                        {% if user == request.user %}
                        <div class="sidebar-box ftco-animate user-profile">
                            <a href="{% url 'accounts:log-out' %}" class="btn btn-hover-color py-2">Log out </a>
                        </div>
                        {% endif %}

                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="row">
                        <div class="col-md-12 heading-section ftco-animate">
                            <h2 class="mb-4"><span>My recipes</span></h2>
                        </div>
                    </div>
                    <div class="row">

                        {% for recipe in user.recipe.all %}

                        
                        <div class="col-md-4 ftco-animate">
                            <div class="blog-entry">
                                <a class="img-2">
                                    {% if recipe.author == request.user %}
                                    <div class="user-events__edit">
                                        <a href="{% url 'inventory:edit_story' recipe.pk %}" type="button" class="edit-event"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                                        <a href="{% url 'inventory:delete_story' recipe.pk %}" type="button" class="edit-event"><i class="fa fa-trash" aria-hidden="true"></i></a> 
                                    </div>
                                    {% endif %}

                                    <img src="{{ recipe.picture.url }}" class="img-fluid" alt="Colorlib Template">
                                </a>
                                <div class="text pt-3">
                                    <p class="meta d-flex"><span class="pr-3">{{recipe.category}}</span><span class="ml-auto pl-3">{{ recipe.added_at | date:"j F" }}</span>
                                    </p>
                                    <h3><a href="#">{{recipe.title}}</a></h3>
                                    <p class="mb-0"><a href="{% url 'inventory:recipe' recipe.pk %}" class="btn btn-black py-2">Read More <span
                                        class="icon-arrow_forward ml-4"></span></a></p>
                                </div>
                            </div>
                        </div>

                        {% endfor %}


                        
                        
                    </div>
                </div>


            </div>
        </div>
    </section>


    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
    </div>

    {% endblock %}

    {% block js %}
    {% endblock %}