foodstories/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from accounts.views import RegisterView, LoginUserView, ProfileView, CustomPasswordResetConfirmView, ResetPassword, ThePasswordChangeView, EditProfileView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('user-profile/<int:pk>', ProfileView.as_view(), name='user-profile'),
    path('log-out', LogoutView.as_view(), name='log-out'),
    path('reset-password', ResetPassword.as_view(), name='reset-password'),
    path('change-password', ThePasswordChangeView.as_view(), name='change-password'),
    path('edit-profile/<int:pk>/', EditProfileView.as_view(), name='edit_profile'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', CustomPasswordResetConfirmView.as_view(), name = 'password-reset-confirm'),
]

foodstories/foodstories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('inventory.urls', namespace='inventory')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('api/v1/', include('inventory.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

foodstories/inventory/api/urls.py
from django.urls import path
from .views import SubscribeAPI

app_name = 'subscribe_api'

urlpatterns = [
    path('subscribe/', SubscribeAPI.as_view(), name='subscribe'),
]

foodstories/inventory/urls.py
from django.urls import path

from . import views

app_name = 'inventory'

from inventory.views import RecipeView

urlpatterns = [
    path('', views.IndexView.as_view(), name='index-page'),
    path('recipes/', views.RecipeView.as_view(), name='recipe-list'),
    path('recipes/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('create-story/', views.CreateRecipeView.as_view(), name='create_story'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('edit-story/<int:pk>/', views.EditRecipeView.as_view(), name='edit_story'),
    path('delete-story/<int:pk>/', views.DeleteRecipeView.as_view(), name='delete_story'),
    
]

foodstories/inventory/models.py
from django.db import models
from django.contrib.auth import get_user_model
from accounts.models import User


class Recipe(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=500)
    text = models.TextField(max_length=3000)
    picture = models.ImageField(upload_to='images')
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name='recipe')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, db_index=True, related_name='recipe')
    tag = models.ManyToManyField('Tag',  verbose_name=("Tags"))

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Recipe'
        verbose_name_plural = 'Recipes'

class Comments(models.Model):
    recipes = models.ForeignKey('Recipe', on_delete=models.CASCADE, db_index=True, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True, related_name='comments')
    text = models.TextField(max_length=1000)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.text}'

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

class Tag(models.Model):
    name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=0)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

class Category(models.Model):
    tagname = models.CharField(max_length=80)
    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.tagname}'

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    
class ContactUs(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=300)
    subject = models.CharField(max_length=100)
    message = models.TextField(max_length=1000)

    added_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.subject} - {self.email}'

    class Meta:
        verbose_name = 'Contact us'
        verbose_name_plural = 'Contact us'

class Subscribe(models.Model):
    email = models.EmailField(max_length=400, unique=True)
    
    class Meta:
        verbose_name = 'Subscribe'
        verbose_name_plural = 'Subscribes'

    def __str__(self):
        return f'{self.email}'

foodstories/inventory/forms.py
from django import forms
from .models import ContactUs, Recipe, Comments

class ContactUsForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'subject', 'message']

        widgets = {
            'name': forms.TextInput(attrs={'id': 'name', 'placeholder': 'Your Name', 'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'id': 'email', 'placeholder': 'Your Email', 'class': 'form-control'}),
            'subject': forms.TextInput(attrs={'id': 'subject', 'placeholder': 'Your Subject', 'class': 'form-control'}),
            'message': forms.Textarea(attrs={'id': 'message', 'placeholder': 'Your Message', 'class': 'form-control'}),
        }

class CreateRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description', 'text', 'picture', 'category', ]

        widgets = {
            'title': forms.TextInput(attrs={'id': 'title', 'placeholder': 'Title', 'class': 'form-control'}),
            'description': forms.Textarea(attrs={'id': 'Short description', 'placeholder': 'Description', 'class': 'form-control'}),
            'text': forms.Textarea(attrs={'id': 'text', 'placeholder': 'Description', 'class': 'form-control'}),
            'picture': forms.FileInput(attrs={'id': 'picture', 'placeholder': 'Picture', 'class': 'form-control'}),
            'category': forms.Select(attrs={'id': 'category', 'placeholder': 'Category', 'class': 'form-control'}),
        }

class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['text']

        widgets = {
            'text': forms.Textarea(attrs={'id': 'Text', 'placeholder': 'Enter Text', 'class': 'form-control'}),
        }

foodstories/inventory/api/views.py
from rest_framework.generics import CreateAPIView
from rest_framework.viewsets import ModelViewSet
from .serializers import SubscribeSerializer
from inventory.models import Subscribe

class SubscribeAPI(CreateAPIView):
    queryset = Subscribe.objects.all()
    serializer_class = SubscribeSerializer

foodstories/inventory/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, DeleteView

from inventory.models import Recipe, Comments, User, Category, ContactUs, Tag
from .forms import ContactUsForm, CreateRecipeForm, CreateCommentForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic.edit import FormMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count

class RecipeView(ListView):
    model = Recipe
    context_object_name = 'recipe_list'
    template_name = 'recipes.html'
    paginate_by = 3

    def get_queryset(self):
        category = self.request.GET.get('category')
        title = self.request.GET.get('title')
        tag = self.request.GET.get('tag')
        
        if title:
            queryset = Recipe.objects.filter(title__icontains=title)
        elif category:
            queryset = Recipe.objects.filter(category__tagname=category)
        elif tag:
            queryset = Recipe.objects.filter(tag__name__icontains=tag)
            print(queryset)
        else:
            queryset = Recipe.objects.order_by('-id')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = User.objects.first()
        context['category'] = Category.objects.all()
        return context

class RecipeDetailView(FormMixin, DetailView):
    model = Recipe
    context_object_name = 'recipe_detail'
    form_class = CreateCommentForm
    template_name = 'single.html'

    def get_success_url(self):
        return reverse_lazy('inventory:recipe', kwargs={'pk':self.get_object().id})

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recent'] = Recipe.objects.order_by('-id')[:3]
        context['category'] = Category.objects.annotate(recipe_count=Count('recipe')).filter(recipe_count__gt=0)
        context['tags'] = Tag.objects.all()
        context['len'] = len(Recipe.objects.all())
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.recipes = self.get_object()
        form.save()
        return super().form_valid(form)

class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['first'] = Recipe.objects.order_by('-id')[0]
        context['author'] = User.objects.first()
        context['index_recipes'] = Recipe.objects.order_by('-id')[:4]
        context['holidays_recipes'] = Recipe.objects.all()[:2]
        context['category'] = Category.objects.all()
        return context

class ContactView(CreateView):
    model = ContactUs
    template_name = 'contact.html'
    form_class = ContactUsForm
    success_url = reverse_lazy('inventory:contact')

class CreateRecipeView(LoginRequiredMixin, CreateView):
    model = Recipe
    template_name = 'create_story.html'
    form_class = CreateRecipeForm
    success_url = reverse_lazy('inventory:recipe-list')


    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class EditRecipeView(UpdateView):
    model = Recipe
    template_name = 'update_story.html'
    form_class = CreateRecipeForm
    success_url = reverse_lazy('inventory:recipe-list')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user != self.get_object().author:
            raise PermissionDenied
        return super(EditRecipeView, self).dispatch(request, *args, **kwargs)


class DeleteRecipeView(DeleteView):
    model = Recipe
    template_name = 'delete.html'
    success_url = reverse_lazy('inventory:recipe-list')

class AboutView(TemplateView):
    template_name = 'about.html'

foodstories/inventory/templates/about.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}

    {% block css %}
    {% endblock %}

    
{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-counter ftco-section ftco-no-pt ftco-no-pb img" id="section-counter">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img d-flex align-self-stretch" style="background-image: url({% static 'images/about.jpg' %});"></div>
            </div>
            <div class="col-md-6 pl-md-5 py-5">
                <div class="row justify-content-start pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <h2 class="mb-4"><span>About Stories</span></h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="100">0</strong>
                                <span>Daily visitors</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="200">0</strong>
                                <span>Stories</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="300">0</strong>
                                <span>Recipes</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 justify-content-center counter-wrap ftco-animate">
                        <div class="block-18 text-center py-5 bg-light mb-4">
                            <div class="text">
                                <strong class="number" data-number="40">0</strong>
                                <span>Users</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- loader -->
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>
{% endblock %}

{% block js %}
{% endblock %}

foodstories/inventory/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    <script src="https://kit.fontawesome.com/baca010a78.js" crossorigin="anonymous"></script>

    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <link rel="stylesheet" href="{% static 'css/aos.css' %}">

    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block css %}
    
    {% endblock %}
     
    
</head>
<body>
{% block header %}
{% include 'header.html' %}
{% endblock %}

{% block content %}
{% endblock %}

{% block subscribe %}
{% include 'subscribe.html' %}
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}
    
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/subscribe.js' %}"></script>


{% block js %}
{% endblock %}
</body>
</html>

foodstories/inventory/templates/contact.html
{% extends 'base.html' %}
{% load static %}

    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}
    
    {% block css %}
    {% endblock %}

    {% block content %}
    <section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-3 bread">Contact Us</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="/">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Contact us<i
                        class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section ftco-no-pb contact-section">
        <div class="container">
            <div class="row block-9">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST">
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.name}}
                            {{form.name.errors}}
                        </div>
                        <div class="form-group">
                            {{form.email}}
                            {{form.email.errors}}
                        </div>
                        <div class="form-group">
                            {{form.subject}}
                            {{form.subject.errors}}
                        </div>
                        <div class="form-group">
                            {{form.message}}
                            {{form.message.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>

                <div class="col-md-6 d-flex">
                    <div id="map" class="bg-white"></div>
                </div>
            </div>
        </div>
    </section>

    <section class="ftco-section contact-section">
        <div class="container">
            <div class="row d-flex contact-info">
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-map-signs"></span>
                        </div>
                        <h3 class="mb-4">Address</h3>
                        <p>198 West 21th Street, Suite 721 New York NY 10016</p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-phone2"></span>
                        </div>
                        <h3 class="mb-4">Contact Number</h3>
                        <p><a href="tel://1234567920">+ 1235 2355 98</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-paper-plane"></span>
                        </div>
                        <h3 class="mb-4">Email Address</h3>
                        <p><a href="mailto:info@yoursite.com">info@yoursite.com</a></p>
                    </div>
                </div>
                <div class="col-md-3 d-flex">
                    <div class="align-self-stretch box p-4 text-center">
                        <div class="icon d-flex align-items-center justify-content-center">
                            <span class="icon-globe"></span>
                        </div>
                        <h3 class="mb-4">Website</h3>
                        <p><a href="#">yoursite.com</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    

    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
    </div>
    {% endblock %}

    {% block js %}
    {% endblock %}

foodstories/inventory/templates/create_story.html
{% extends 'base.html' %}
{% load static %}


    {% block title %}
    <title>Stories - Free Bootstrap 4 Template by Colorlib</title>
    {% endblock %}

    {% block css %}
    {% endblock %}


{% block content %}
    <!-- END nav -->
    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" class="bg-light p-5 contact-form" method="POST" enctype="multipart/form-data">
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {{form.non_field_error}}
                        <div class="form-group">
                            {{form.title}}
                            {{form.title.errors}}
                        </div>
                        <div class="form-group">
                            {{form.description}}
                            {{form.description.errors}}
                        </div>
                        <div class="form-group">
                            {{form.text}}
                            {{form.text.errors}}
                        </div>
                        <div class="form-group">
                            {{form.category}}
                            {{form.category.errors}}
                        </div>
                        <div class="form-group">
                            {{form.author}}
                            {{form.author.errors}}
                        </div>
                        <div class="form-group">
                            {{form.picture}}
                            {{form.picture.errors}}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>


    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen">
        <svg class="circular" width="48px" height="48px">
            <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
            <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00" />
        </svg>
    </div>
    {% endblock %}

    {% block js %}
    {% endblock %}

foodstories/inventory/templates/delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

foodstories/inventory/templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="/">Stories<span>.</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'inventory:index-page' %}" class="nav-link">Home</a></li>
                    <li class="nav-item"><a href="{% url 'inventory:about' %}" class="nav-link">About</a></li>
                    <li class="nav-item"><a href="{% url 'inventory:recipe-list' %}" class="nav-link">Recipes</a></li>
                    <li class="nav-item"><a href="{% url 'inventory:contact' %}" class="nav-link">Contact</a></li>
                    {% if request.user.is_authenticated %}
                    
                    <li class="nav-item"><a href="{% url 'accounts:user-profile'  request.user.pk  %}" class="nav-link">
                        {% if request.user.profile_pic %}
                        <img src="{{ request.user.profile_pic.url }}" style="width: 30px; height: 30px; border-radius: 50%;" alt="">
                        {% else %}
                        <img src="{% static 'images/default-profile-icon-16.jpg' %}" style="width: 30px; height: 30px; border-radius: 50%;" alt="">
                        {% endif %}
                    </a></li>

                    <!-- <li><a href="{% url 'accounts:log-out' %}" class="btn btn-black px-3 px-md-4 py-3">Log out</a></li> -->
                    {% else %}

                    <li><a href="{% url 'accounts:login' %}" class="btn btn-black px-3 px-md-4 py-3">Sign in</a></li>
                    
                    {% endif %}
                
            </ul>
        </div>
    </div>
</nav>

foodstories/inventory/templates/subscribe.html
<section class="ftco-subscribe ftco-section bg-light">
    <div class="overlay">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 text-wrap text-center heading-section ftco-animate">
                    <h2 class="mb-4"><span>Subcribe to our Newsletter</span></h2>
                    <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It
                        is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="" method="POST" class="subscribe-form">
                                {% csrf_token %}
                                <div class="form-group d-flex">
                                    <input type="email" name="email" id="email">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                    <div id="message">
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>